// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MsgId {

  /// <summary>Holder for reflection information generated from msg_id.proto</summary>
  public static partial class MsgIdReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtc2dfaWQucHJvdG8SBU1zZ0lkKlIKBU1zZ0lkEg8KC01TR19JRF9OT05F",
            "EAASGwoXTVNHX0lEX1BMQVlFUl9MT0dJTl9SRVEQARIbChdNU0dfSURfUExB",
            "WUVSX0xPR0lOX1JTUBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MsgId.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("MSG_ID_NONE")] None = 0,
    /// <summary>
    ///@PlayerLoginReq;MsgIdPlayerLoginReq
    /// </summary>
    [pbr::OriginalName("MSG_ID_PLAYER_LOGIN_REQ")] PlayerLoginReq = 1,
    /// <summary>
    ///@PlayerLoginRsp;MsgIdPlayerLoginRsp
    /// </summary>
    [pbr::OriginalName("MSG_ID_PLAYER_LOGIN_RSP")] PlayerLoginRsp = 2,
  }

  #endregion

}

#endregion Designer generated code
